### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by mitaa** [contain-rs/vec-map#1]
The url (https://contain-rs.github.io/vec-map/vec_map) provided in the Readme produces a 404 error since the `gh-pages` branch with the documentation doesn't exist.

**Comment by apasel422** [comment]
This should be fixed once Travis runs successfully for the first time.

@Gankro Could you configure the Travis GH_TOKEN env var (using @FlashCat as usual) when you get the chance?

**Comment by FlashCat** [comment]
I set the token, but can't seem to find the old notes on setting up the gh-pages branch correctly. Also travis seems to have changed on me and now I can't seem to convince it to kick off a build regardless.

**Comment by apasel422** [comment]
https://github.com/contain-rs/linked-list/issues/1

**Comment by Gankra** [comment]
Ok everything's set up. Can't seem cajole travis into kicking off, though.

**Comment by apasel422** [comment]
The docs are now hosted.
