### ISSUE TITLE
get function takes a pointer to usize?

### ISSUE THREAD

**Issue by Binero** [contain-rs/vec-map#10]
Why does the get function (amongst others) take a pointer to usize, as opposed to just a usize? 

https://github.com/contain-rs/vec-map/blob/master/src/lib.rs#L433
https://github.com/contain-rs/vec-map/blob/master/src/lib.rs#L457
https://github.com/contain-rs/vec-map/blob/master/src/lib.rs#L475
https://github.com/contain-rs/vec-map/blob/master/src/lib.rs#L475

**Comment by apasel422** [comment]
The reason is essentially consistency with the other map types (e.g. `BTreeMap`).

CC contain-rs/bit-set#5.

**Comment by Binero** [comment]
Seems like a waste of resources to me.

**Comment by apasel422** [comment]
With inlining and other optimizations, I'd say the main downside to the current situation is syntactic noise. I'd be in favor of merging a pull request that changes these to take the `usize` by value.

**Comment by Binero** [comment]
Such a change would be a breaking change. If I were to write a PR, would it be approved?

**Comment by apasel422** [comment]
Other people from @contain-rs/owners can chime in on whether such a minor change is worth breaking backwards compatibility, but if we do merge such a PR, we can bump the crate's version to indicate that there was a breaking change.

**Comment by Binero** [comment]
cc @reem

**Comment by Gankra** [comment]
We have 12 reverse dependencies https://crates.io/crates/vec_map/reverse_dependencies and all of them are presumably going to break if we make this change. That seems way too brutal for something that I'd be surprised to not see inlined away.

CC @HeroesGrave @simnalamburt @andelf @johanneskoester

**Comment by johanneskoester** [comment]
In my opinion, it would be better to get the API right at this early stage of rust instead of breaking later when hundreds of packages depend on this.

**Comment by Binero** [comment]
I would have to agree with this.

**Comment by HeroesGrave** [comment]
I'm fine with it being changed. In all the cases where I used it I was calling `vec_map.get[_mut](&index)` anyway.

Assuming all of the downstream crates aren't using wildcard dependencies, it really shouldn't be that much of an issue anyway.

**Comment by Binero** [comment]
Well looking at what happened when libc updated recently, I wouldn't make that assumption.

**Comment by Gankra** [comment]
Upon reflection, if a trait is ever added, it can trivially dispatch to the proposed interface. So :+1:  let's ship it.

**Comment by Binero** [comment]
Do we have a consensus here that the get function should take a value?

**Comment by apasel422** [comment]
@Binero I think so. You can submit a PR if you'd like.

**Comment by apasel422** [comment]
This was closed in #11.
