### ISSUE TITLE
Build error for rustc 1.12 and vec_map 0.6

### ISSUE THREAD

**Issue by dan-t** [contain-rs/vec-map#19]
Hi,

I'm getting a build error for vec_map 0.6:
https://travis-ci.org/dan-t/rusty-tags/builds/153615676

It's a bit irritating that I'm getting the error only for the current
rustc `beta`, but not for the `stable` and the `nightly`.

Any ideas?

Greetings,
Daniel

**Comment by apasel422** [comment]
Duplicate of #18.
