### ISSUE TITLE
impl serde::Serialize

### ISSUE THREAD

**Issue by kbknapp** [contain-rs/vec-map#29]
https://serde.rs/serialize-map.html or something similar.

**Comment by tnajdek** [comment]
I was looking for the same thing and browsing the source I've realized this is actually implemented, just not mentioned anywhere. All you need is to enable "***eders***" feature in `Cargo.toml`:

    vec_map = { version = "0.8.0", features = ["eders"] }

**Comment by oherrala** [comment]
I think this issue can be closed. There's already feature called "eders" and pull request (#40) to introduce feature "serde".
