### ISSUE TITLE
Inconsistent docs

### ISSUE THREAD

**Issue by apasel422** [contain-rs/vec-map#3]
Not sure if this was intentional, but the nightly Travis build generates the docs without the nightly features enabled:

``` yaml
    - cargo doc --no-deps
after_success: |
    [ "$TRAVIS_RUST_VERSION" = nightly ] &&
```

I don't know if we want to host the stable docs or the nightly docs, but the configuration should be changed to the following, regardless:

``` yaml
    - cargo doc --no-deps $FEATURES
```

**Comment by Gankra** [comment]
ah-aaaa right we don't have stability features... I guess I would publish the nightly docs...? Gonna cause confusion though.

**Comment by apasel422** [comment]
I'll leave it to you to decide, but we should at least build the docs with the correct features. I'll edit the file directly.
