### ISSUE TITLE
Have serde feature be called serde

### ISSUE THREAD

**Issue by jonhoo** [contain-rs/vec-map#38]
The `serde` feature for `vec-map` is currently counter-intuitively called `edres`, presumably because of https://github.com/rust-lang/cargo/issues/1286. There is a workaround for this problem in `serde` itself (https://github.com/serde-rs/serde/blob/v1.0.0/serde/src/lib.rs#L222-L260), whereby you depend on `serde` with the `derive` feature, which in turn re-exports `derive(Serialize, Deserialize)` from `serde_derive`. This allows the feature of the top-level crate (in this case `vec-map`) to also be called `serde`. Or rather, it allows you to not explicitly add a feature called `serde`, but instead rely on the behavior that optional dependencies are implicitly also features.

**Comment by Gankra** [comment]
sgtm? I completely missed all this happening.

**Comment by Boscop** [comment]
Any update on this? :)

It would just be a few lines, like this:
https://github.com/softdevteam/vob/pull/10/files
