### ISSUE TITLE
Is there a fork that's maintained?

### ISSUE THREAD

**Issue by Boscop** [contain-rs/vec-map#42]
I would like to add the methods get_or_insert and get_or_insert_with, but this crate won't accept PRs it says. Is there a more maintained fork?

**Comment by clarfonthey** [comment]
I believe that the orignal maintainer was looking for folks to pick up contain-rs instead of just putting it into maintenance mode. Unfortunately, no one took up the offer.

Not sure if the offer is still open, though.

**Comment by camsteffen** [comment]
> I would like to add the methods get_or_insert and get_or_insert_with

Use the Entry API.

> Is there a more maintained fork?

The message on the readme seems like it is written to scare people away from using this crate. But my impression is that there isn't a lot of room for improvement for `VecMap` and this is still perfectly fine to use. And I think that is why there isn't a replacement rising up in the rust community.

**Comment by clarfonthey** [comment]
Honestly, I disagree-- there are definitely new APIs that have been made since the library was put up and you always want to make sure someone can maintain it.

No one really stepped up when Gankra didn't have any more bandwidth to maintain collect-rs but I feel like it could definitely use the love, if folks had love to provide.

**Comment by camsteffen** [comment]
> there are definitely new APIs that have been made since the library was put up

Would you mind sharing some of those? I haven't been able to find a viable replacement for VecMap.

> No one really stepped up when Gankra didn't have any more bandwidth to maintain collect-rs but I feel like it could definitely use the love, if folks had love to provide.

That's sad to hear. I'm not really aware of that history. But I don't see any invitation for maintainers.

Do you think VecMap could "use the love" specifically or are you referring to collect-rs in general? Do you have specific improvements in mind?

**Comment by clarfonthey** [comment]
By new APIs I mean, new things that are added to other maps that might make sense to add to this one. Also, collect-rs in general could use some love, but I feel that folks who have the time, resources, and desire to maintain these should step up. They're already being replaced by other libraries.

**Comment by Boscop** [comment]
@clarfon By which other libraries?

**Comment by pczarn** [comment]
I've restarted maintenance. Further, I would be interested in hearing about alternative libraries

**Comment by michaelbeaumont** [comment]
@pczarn do you think we should publish a release on crates.io?
