### ISSUE TITLE
Use newtypes as keys

### ISSUE THREAD

**Issue by piegamesde** [contain-rs/vec-map#47]
`VecMap` perfectly fits my current use case, except that my integer keys are newtype-wrapped for safety reasons. It'd be really cool if any types that can convert from and into `usize` could be used. The inner workings need not be changed, and I think the interface can even be extended in a backwards-compatible way if that's desired.

**Comment by clarfonthey** [comment]
Read the readme.

**Comment by piegamesde** [comment]
I recommend having a look at [`typed-index-collections`](https://docs.rs/typed-index-collections/3.0.3/typed_index_collections/). One can use `TiVec<K, Option<V>>` similarly to `VecMap`, although the API is of course more `Vec` than `Map`.

**Comment by pczarn** [comment]
This is out of scope for us. However, I would be interested in solving this some day
